---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "service.name" . }}
spec:
  selector:
    matchLabels:
     app: {{ template "service.name" . }}
  replicas: {{ .Values.replicas | default 1}}
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: {{ template "service.name" . }}
        component: "app"
        image: {{ .Values.image.name }}-{{ .Values.image.tag }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: {{ template "service.name" . }}
      containers:
      - name: {{ template "service.name" . }}
        image: {{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        command:
          - "/bin/sh"
          - "-c"
          - "cd $APP_DIR && node service_subscribe.js"
        envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: secret
        resources:
{{ toYaml .Values.resources | indent 10 }}
